# Generated by Django 3.2.4 on 2023-05-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_followerevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerevent',
            old_name='user',
            new_name='owner',
        ),
    ]
