# Generated by Django 3.2.4 on 2023-05-18 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_rename_user_followerevent_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowerEvent',
            new_name='EventFollower',
        ),
        migrations.RenameField(
            model_name='eventfollower',
            old_name='owner',
            new_name='user',
        ),
    ]
