# Generated by Django 3.2.4 on 2023-05-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230518_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventFollower',
        ),
    ]
