# Generated by Django 3.2.4 on 2023-05-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
    ]
