# Generated by Django 3.2.4 on 2023-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
