# Generated by Django 3.2.4 on 2023-06-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_staff',
        ),
    ]
