# Generated by Django 3.2.4 on 2023-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
