# Generated by Django 3.2.4 on 2023-06-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
