# Generated by Django 3.2.4 on 2023-06-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_rename_image_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
