# Generated by Django 3.2.4 on 2023-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_sqpxy8', upload_to='images/'),
        ),
    ]
