# Generated by Django 3.2.4 on 2023-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upvotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='upvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
