# Generated by Django 3.2.4 on 2023-05-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upvotes', '0002_auto_20230522_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='content',
        ),
    ]
