# Generated by Django 3.2.4 on 2023-05-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upvotes', '0003_remove_upvote_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='updated_at',
        ),
    ]
