# Generated by Django 3.2.4 on 2023-05-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0006_auto_20230518_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerEvent',
        ),
    ]
